#server:
#  port: 50392
#  error:
#    include-message: always
#
#spring:
#  config:
#    import: file:env.properties
#  profiles:
#    active: test
#  application:
#    name: sms-report-service-test
#  datasource:
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    url: jdbc:sqlserver://${DB_DATABASE}
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.SQLServerDialect
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#
#
#    ##LOGGING CONFIG
#
#logging:
#  file:
#    path: E:\Apps\sms-report-service\logs
#    name: ${logging.file.path}/sms-report-service.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#
#  level:
#    com.sahay: debug
#    org.springframework.web: error
#    org.hibernate: error
#
#
server:
  port: 50392
  error:
    include-message: always

spring:
  profiles:
    active: prod
  application:
    name: sms-report-service-prod
  datasource:
    username: sa
    password: '@R@y5#MFI!!2020_sahay'
    url: jdbc:sqlserver://172.16.1.15:53500;databaseName=mobile_banking;trustServerCertificate=true;encrypt=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

    ##LOGGING CONFIG
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  file:
    path: E:\Apps\sms-report-service\logs
    name: ${logging.file.path}/sms-report-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

  level:
    com.sahay: debug
    org.springframework.web: error
    org.hibernate: error

